table 'Active SVC KPI'
	lineageTag: ee41a7e1-02d5-4991-b698-9904c4f9c154

	column 'Service centre'
		dataType: int64
		formatString: 0
		lineageTag: ce9810bb-a13d-40d3-b302-1770ab135033
		summarizeBy: sum
		sourceColumn: Service centre

		annotation SummarizationSetBy = Automatic

	column Engineers
		dataType: int64
		formatString: 0
		lineageTag: b0548891-cbb3-47f5-b916-20aa13f3e32b
		summarizeBy: sum
		sourceColumn: Engineers

		annotation SummarizationSetBy = Automatic

	partition 'Active SVC KPI' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WsjRV0lEyNzdTio0FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Service centre" = _t, Engineers = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Service centre", Int64.Type}, {"Engineers", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

