table 'active aging'
	lineageTag: 1c820cbe-204a-441b-929d-cc770b0838bf

	column Aging
		dataType: string
		lineageTag: 09e4f2f8-b2b8-4277-83bf-2d41ceb74dc2
		summarizeBy: none
		sourceColumn: Aging
		sortByColumn: Sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Open
		dataType: int64
		formatString: 0
		lineageTag: c110927c-a094-4903-9379-3270a415fa62
		summarizeBy: sum
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

	column Sort
		dataType: int64
		formatString: 0
		lineageTag: 0fa2e440-efe1-447f-85bb-b0880be2c524
		summarizeBy: none
		sourceColumn: Sort

		annotation SummarizationSetBy = Automatic

	column Hold
		dataType: int64
		formatString: 0
		lineageTag: 36b1fa9f-1a76-4302-9010-5607b892112c
		summarizeBy: sum
		sourceColumn: Hold

		annotation SummarizationSetBy = Automatic

	partition 'active aging' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMtA1NFBwSawsVtJRMrQwAJEgbGSgFKsTrWRooGsEl7YwBRJGIIYhWNLIQNcYLmkOkjQGYjNTsGRMqYGBcSpC3gxktAkQmwLlYwE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Aging = _t, Open = _t, Sort = _t, Hold = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Aging", type text}, {"Open", Int64.Type}, {"Sort", Int64.Type}, {"Hold", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

