table Decomposition
	lineageTag: 3fe8c9f9-2e81-4212-b9b5-aa0089dbc3b1

	column Product
		dataType: string
		lineageTag: 41b566bc-8d16-49cd-8a77-395ac0259f8c
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Sub-Product
		dataType: string
		lineageTag: e5291805-8b1b-4d26-9af1-8c0344f9f4a5
		summarizeBy: none
		sourceColumn: Sub-Product

		annotation SummarizationSetBy = Automatic

	column Column1
		dataType: int64
		formatString: 0
		lineageTag: 1e8b80f8-2f4e-4e2b-8492-12058bca5fc3
		summarizeBy: sum
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	partition Decomposition = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCnJ0VtJRCoZQhkbGSrE6MEFPvzAFMMPI0BBJONzTDyJsaGAEEXZ1A/JcIEIGSEJuIMLQDFmVP0TM2AQsFu4LUuUDpmB2gzkhUDFzC6XYWAA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Product = _t, #"Sub-Product" = _t, Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Product", type text}, {"Sub-Product", type text}, {"Column1", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

