table 'Defects Repetition Branch Wise'
	lineageTag: 844ae545-2285-42a6-8785-9766a1d18fe8

	column Branch
		dataType: string
		lineageTag: 6828bdc5-bac4-48ea-9278-27cfc2e2c643
		summarizeBy: none
		sourceColumn: Branch

		annotation SummarizationSetBy = Automatic

	column Defect
		dataType: string
		lineageTag: bccf7aa4-efba-4157-98d1-04fc386e2352
		summarizeBy: none
		sourceColumn: Defect

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: int64
		formatString: 0
		lineageTag: a038bd2a-3a5e-44c1-976b-fd83bfd6953f
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column Sort
		dataType: int64
		formatString: 0
		lineageTag: 97d2d217-4a6a-4af0-866d-1fd37cfc3f0f
		summarizeBy: none
		sourceColumn: Sort

		annotation SummarizationSetBy = Automatic

	partition 'Defects Repetition Branch Wise' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("ddGxDoIwEIDhVyHMDEKhLSNRAxhx0DARBqINIagMyPtbOLm2gMullz+kX0pR2Fme2Y596ZpeWGnfD0JuNJDDtUtHZWvfdc/mXcuFj9XT6qF6VbV4yFPgyUG0FFe9dRZVK7vc/PFLX8u3z3Bv8dqAjmPK++S4UhGKqjlvq6Aqla9UkEwVUSrIpmpCgyrOryuVz1A1Z13logqqUjGKKkimihJUQV68FUdVlGz8QY6qOWsq5qEKqlJxgipIf1WQFyqGqlOUrjIPUQXZRIc7ZM1ZQwchyqAqdMhRBclEs99blV8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Branch = _t, Defect = _t, Value = _t, Sort = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Branch", type text}, {"Defect", type text}, {"Value", Int64.Type}, {"Sort", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

