table 'Defect Code analysis'
	lineageTag: 05a55d17-e3b3-4bcb-a817-625023b00430

	column Column1
		dataType: string
		lineageTag: fc601d83-9176-4a5c-bf74-4a983c1ad0a5
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column CY
		dataType: int64
		formatString: 0
		lineageTag: e2f32f75-5c6f-470a-a569-4276e50ec965
		summarizeBy: sum
		sourceColumn: CY

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column PY
		dataType: int64
		formatString: 0
		lineageTag: 150305a6-e6f0-4e37-8774-6f16554df82d
		summarizeBy: sum
		sourceColumn: PY

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition 'Defect Code analysis' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCnAMClHSUTI2MQGRpmZKsTrRSp5+/sFArqGROYg0MIIIBrkGALlGJqYgEqoywNnJB6TGGKTdyMgAotLF0xHEtTAGSVlaKsXGAgA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, CY = _t, PY = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

