table 'Open/Hold KPI'
	lineageTag: 170e4387-46ea-4a34-911c-ea91ba58dc66

	column Total
		dataType: int64
		formatString: 0
		lineageTag: 21526c0c-1271-4d67-9f32-73dac6a07d58
		summarizeBy: sum
		sourceColumn: Total

		annotation SummarizationSetBy = Automatic

	column Open
		dataType: int64
		formatString: 0
		lineageTag: 9d45d0d1-4f9d-42d9-9a6a-0255236c1156
		summarizeBy: sum
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

	column Hold
		dataType: int64
		formatString: 0
		lineageTag: acce7fc0-19ef-49fe-ae6a-e85fec836c87
		summarizeBy: sum
		sourceColumn: Hold

		annotation SummarizationSetBy = Automatic

	column '>180 days'
		dataType: int64
		formatString: 0
		lineageTag: cab2ba26-2e13-409f-9e62-6a3cac0e7213
		summarizeBy: sum
		sourceColumn: >180 days

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition 'Open/Hold KPI' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMjQ0NlbSUbIwNwOSRibmQNLQ1EApNhYA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Total = _t, Open = _t, Hold = _t, #">180 days" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Total", Int64.Type}, {"Open", Int64.Type}, {"Hold", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

