table P/N
	lineageTag: 838070aa-1a33-4433-8e1f-6659be485255

	column Branch
		dataType: string
		lineageTag: 045e3bd2-b229-4282-8cdf-bdc786c4a491
		summarizeBy: none
		sourceColumn: Branch

		annotation SummarizationSetBy = Automatic

	column Parts
		dataType: int64
		formatString: 0
		lineageTag: b6fe7f57-1089-440e-acb0-531dff3f4288
		summarizeBy: sum
		sourceColumn: Parts

		annotation SummarizationSetBy = Automatic

	column 'Non Parts'
		dataType: int64
		formatString: 0
		lineageTag: a7be4fe4-739c-4446-b380-acb620cdac5f
		summarizeBy: sum
		sourceColumn: Non Parts

		annotation SummarizationSetBy = Automatic

	partition P/N = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8nL0VNJRsrAEEqZmSrE60UqOHr5AjrkpSNgULOIbChKxtAASJkZgEffQICDHDKTGzBIs4uzhCtJlCFEYGwsA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Branch = _t, Parts = _t, #"Non Parts" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Branch", type text}, {"Parts", Int64.Type}, {"Non Parts", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

