table 'Parts replacement'
	lineageTag: 8e5b8f9f-4ebf-4419-ba26-c84ff5e55974

	column Part
		dataType: string
		lineageTag: 87844c8a-f2af-4449-b6e6-cb53e845d953
		summarizeBy: none
		sourceColumn: Part

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: int64
		formatString: 0
		lineageTag: 87d986e5-ad0f-4f26-927f-ea1032fe744d
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Parts replacement' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wcs7PLShKLS7OL1LSUTIxVYrViVbyLy1Jyc8vUghwdgIKGhmDBT3zkMSMTcBirmWJBflFiSVgzWYQMef8vJTUPIh5pmZgId98oAoFqAFOPi7OIFOBqmMB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Part = _t, Value = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Part", type text}, {"Value", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

