table 'RNP Number'
	lineageTag: ed9eca9e-dbaf-4dc8-aa8e-295874e80e9e

	column Type
		dataType: string
		lineageTag: 8ae6c48f-d94c-498e-8f79-1d2b3721cae6
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Number
		dataType: int64
		formatString: 0
		lineageTag: 69046872-a42c-43d9-8d94-aef74e2e0b3f
		summarizeBy: sum
		sourceColumn: Number

		annotation SummarizationSetBy = Automatic

	column %age
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 1150d500-cdd5-45cf-a986-fb8b79176044
		summarizeBy: sum
		sourceColumn: %age

		annotation SummarizationSetBy = Automatic

	column Pending = 7862- [Number]
		formatString: 0
		lineageTag: 804f5eb3-78df-445d-8d42-4df3aca66e0f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'RNP Number' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlII8gtQ0lEytjAyAFIGeiYWphZKsTrRSsZQGSMzC1OwjLGJoSlYJqbUwMA4FSZvaGxqDpY3NDcyU4qNBQA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Type = _t, Number = _t, #"%age" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Type", type text}, {"Number", Int64.Type}, {"%age", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

