table 'RNP >180'
	lineageTag: 17d5d591-ecc5-4776-824c-53812a2cfd93

	column State
		dataType: string
		lineageTag: f3571ba0-a208-4517-93e6-f2560bd6340d
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 0dd482ab-fe7e-43b8-9d77-1115e2ad34ec
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column 'Model Code'
		dataType: string
		lineageTag: 0a93bc60-25d1-4fe4-8ff6-984fdb680bb9
		summarizeBy: none
		sourceColumn: Model Code

		annotation SummarizationSetBy = Automatic

	column 'Defect Category'
		dataType: string
		lineageTag: 57627d89-d696-4339-a456-62bf8e0f5546
		summarizeBy: none
		sourceColumn: Defect Category

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: ee429a27-3dc8-4309-9137-8cbe41da6b62
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Serial No'
		dataType: string
		lineageTag: 5acaf325-7574-407d-9413-2e4bf3b1893d
		summarizeBy: none
		sourceColumn: Serial No

		annotation SummarizationSetBy = Automatic

	column 'AC Error Code'
		dataType: string
		lineageTag: ff88999f-e7c7-4d10-85c7-9a7fab98b0f5
		summarizeBy: none
		sourceColumn: AC Error Code

		annotation SummarizationSetBy = Automatic

	column 'Days Open'
		dataType: int64
		formatString: 0
		lineageTag: 1ebd3563-418a-464d-bddf-1c5e3d885595
		summarizeBy: sum
		sourceColumn: Days Open

		annotation SummarizationSetBy = Automatic

	column 'RNP Number'
		dataType: string
		lineageTag: 3edeca91-9048-4f89-a3f8-a2af79531770
		summarizeBy: none
		sourceColumn: RNP Number

		annotation SummarizationSetBy = Automatic

	column 'Service Centre'
		dataType: string
		lineageTag: 714a7545-68f6-45db-a2ac-ec04c8063f5c
		summarizeBy: none
		sourceColumn: Service Centre

		annotation SummarizationSetBy = Automatic

	column 'Engineer Name'
		dataType: string
		lineageTag: d79429b1-4c8c-4a05-9dc3-e1bc21dcc30f
		summarizeBy: none
		sourceColumn: Engineer Name

		annotation SummarizationSetBy = Automatic

	partition 'RNP >180' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("zVzZcuPIlf2VDD51R7inkNjxmCQgAsRaWKiiPH6gq9gtuVViDSW1o+dr/C3+srn3JkFiB6tnxmE7QqJIVePorucumX/+8yJPMtVUDIUrlmEqfPGnRbRmhZdvg5XH7tM8cn9Y+d6P8L6At5PSDyJ4XYo4iFgi3Ap+CPOg8BOxDvIAfqqK6iN3NsmDp8FP6fvbl+PxxLLVEn/KvAS+GVzJROYquqraCvy8Oh6fn15++eAf9m/wHd5Rubr4y59qdLqmKLptaBY+2Yt2bCVyDxG58GCWh4jBy0Uk8IVIkionHD995HaZfMLf9H7bfzue9m/HUwOFomViV3FHUQ0bfnaffnl62z8z9+n12/P+9w/e6QTAV8cvhz4gVVM0S3VQXFUSfKw85kXeqszTJFgVPwjxQAJb+oDPC1nhizxGcD4Cy0Sy8sOK0N4AUkeQGtcda0RUit1CBko0VBV/N008Vgaxx5ZBFAXJmq2qokxjL//JLVY/CTdvYIzha46IXC/yg8b3qkhAnZ8kwuBlQJmKkQk/USyTG9qsGBW9ARY0oHDd5A58svwPtza7Av9OENnKD0q2Tot7MDaEWhQihu/r1M8aGs4ltGFDU8xMuPeKqpoOqjg7/v1w+lA8Hk9vbPV0+vz+9DYISrNNAyUoolA0NQtvxVWSCBZWsUAIy8AXUqdlctGn8xGMn0+Ja1cptmpZt0LSuabohu2o8ElR+SIRTVGBdfmByzIBL8gB8kSUIsTXS5GsRZRKZ0FF8rtkKxX5+v7ctjRTUTOxjDXFsDg6WnJ8ej182D79FSzy6fjSB6VaiuKopkEQArC1OmpkkXjApxeP+9P+5W+HwxsrpK1mVbIRKIx1lbuiaKjR8aUa4yOAYmfBLSN31VEmGJquKtp3GpquctCralpTXiH/jm1ORtZ3A7S1cMZRE6GauuU4N+sVhK4q5DZTsMRG7GqL6wITBGwzDoz0mgjFUUxVG4kgSsv+dcXRddKrK0JUbdcHRJKmGcvQ2CgZ+EFebeEZkB0E6JQESAJTVxJXfvh6fDv0ValaqqVdPgfdvbydjs8flu9vb8eX1x40DG6GqZlz8nL3z4cTmtwjKgLt7SHIRdiMGt6UJsFDtw+KrZm2JX0FzOyZvOADQHw5fL44RFtwBoqYy8CR+eKSpkJwTVay7UiewgB7P4PnPoQsaKmcniofBi+5Y3YAgOJIolufQbL28gxyM0UJEYYijiFwiCDCpF2uMR/tXMCzFG6Nw36QOFbHr99Oh9fXXr68KyC7cJLLJA7VMbg9Z9ZoRrVdQxzdCYqhdyIP3AsotKLdVPYB6y7vDAc8a1I4OlAN29LgPTLY5GMzhIqX1z38h/evj/tOBIUcBIJbiigS0nzI3+bCKEjJdkzLGI0DXWyA2TBUFNg697yEld7KbwHMIbi7LITYvyAOhIGdpNVWIWDTd5B9xqTFeSYePioOtyno3AIOtWk4to1/TJmWIrqYdRGJmBWB6yMBatq2B/JDghPX8qrjwKB5cxXdDWmY5UxrEKiNrhBbiFnQse+ln0aCJQHKCUVRliJnWS5cr/DJISPhn8VEmbAOmUOWTjr8FKlg6ar6HWJSbYv4bCwEE2svWQUSWrDZgKQSkQs08dxz3R2ZvwuUq4ERXkGkuEZPJz/ziNF8k7mqAZHanDd8rqO+NyJgCK4dzl0RbTyvBFUma8JRZ2nwrEBceWqdo4fg6Jz8UIE6gthDP8t0UVmK6XBJaQAVJA1WoiRyQhREQcZ2whXbIV0+iHgtcn9xE39WMdNYmmZTcXObO1pAbAzNICVtRBS02H1UucjugcIgSRVJX24FeGfe4DabZDfLbcAxxUaFusLGKLB6PuxfQG6sOJx+e/p8GMVon+XXdoYgRlyxSM70NBaItPBLoviQpRPvEvHdmQqpyoGkc6LDs6goA2kOR8nt4HlZjnYlhResREQmuN4EDVtDeYk4D8pCXLPh5mz45+ew3/bPv7XoA2REb4lMVbGnbd9SbC5FWrCCiSBnqzRxgzKAxESSOT7uv349fGHi9PP+7ZFVkOgXUyQa7c2/n2BbHFk0IFIIz7wfKAokChJvuGFFGlWIjSqN1HcZJEMZ87u8r7zEVV6b1p/c1U/F2+HbN/mg2jORa4FncqhY0TMLIEev7APLTkcgXUBk4HWT4sCPxbfD56efnz7XxL+rZBV4jmPpi+n0DqL9Il6ffh7wYCA/dTZNbmCvuwoeJ+vfCdKho6qJe2P2PCepGMqlOPagthRbCv6XJBXDt6xmq7NZivR6V4CuJP0849AHXcDUNRNj8ipNSSjep8zLy7otkOwPh68sfNy/DKhV+uRq3MAooG1Whg5VmjonEEdxKM8Xmee1yusMowHw9X/+g1FSYq4vgnXler1gUYAb0AsSkbOqs+bLl8PL66GrqYePUNJoNp+TEIRjSvZ5ugNC0QLmxQziauLSQ9cpYUir0mfyteRf4TT/CtdchT99hqXqkK1M3aQ/uYDw2YjyF0hMFKsfgGOh4sBUxLnXhfmqYmEFcYuKsG4qL/IgvFCgdlMACFldsnbi/zJWuKqbkyQInc82dBXF6i3zZtyv+3QNmAlDJ2s16+CXkkRcK8dzSbu6u+vI0L3nUDTbk9wC0Vi2zicLsh+Em/wo09TOc4MiFtRCXFcbMKwSP6jk95tUG/tcM2w+Y2G6YqmaQ+VuGt+lecmyNEjKn1CbkP4knByCq3hgYulWeS58SJcMv7o9H4ireHkVmepNdJzO1JFrEHZnRIfVokXmd24hQiEUeiWI7iyTzTidXafAFS9tsEYMHa6RdCIXBoTHeUwmIEe55bsCyT6kTAxjCOn9tP8bK97/CmUSWz3u32UEG+MWKKnlZG8OTL7YgqoMezaQAVUkVIl3D2KKyoA9pPSce4GWToVRXR1tAA++dMkXklWjf1POFJJVbqm6Nac4MC6gXp1EsxP+DuqP/02GIQbNNVXG7AnrhmRka7IbDkaSe3d5sIaHInHAJ7nJWRjwEVo1QkGjScS60QKp68TRJLOrTJCF08i6JmFpNcKBGEJRSZkIzYQtgfE9eG2iJS1a3EEmWbIYooIIGZDqnu0Af75wrHknK7aqpimEaYzUqx2pYeiUncPT4fNbzWLZ6vDydjr8UK7yH9kP2BrnP0J83xDmBxFhe9xvBSz4MExvjljrT9w2NceZkiPp1LF5M2Khhbd6ABuxYxAXPMyNbF1lpRiPVFLF63tScfl4OH19eu3Xj2IDZbfhqLPQIFH+kbZWbe8jAUAn4ViWQZ2SCQQQuCzHRFeAINhtRoY+xsY8LaoI47cnS3xZRxfBshBrce37RVP9LYMcENKepk3jAQID5EFdyFIf0sdaNDIxPj+GGueioxoNxPaiCoPr4OdhJmgD8QUbN+xpNAhFp0i1DRJgc6Fo+x8igJDgglGni/HaRtKU8F4O7gZthsveFiR9Z1ZjJjD2uX67KII7GQl6CU5UQFvYsnKBmQJ3kToUs0Z1br+pHADNKBHM2lI0NGvIv1svLyDblWhbacz+8x1kajY6EkRJMaz22pVr1D4JudVBHc0xd4WpWMq0xeO8orb4/mAsicH2mS8eIPeFftPACvigbE5VlmfSOSgrHbuB2OgGZU11A9sB31SwtYtic4N1gBRhYPTpYlCKl2CFdaF/FRjk582m4ZKTDQidtKk4NvWvBhsQ3cEsTsvMGcO7E8GDSM6E4TtsT2u2cobr7Zo8W47Oxwd8HdhgjLptX9MoDd4RJ/xAplf77nCLNRkftZjnrj03VeqcZvvTG5b/4vNnin+/s9Phv94Pr8MZU1NkMwcytpesg8TzcpnNN2KVZhDhMFIkC1lWQCSBAFpWF+sT5yWAqcYXhpS8hMeYXJ/2V03RTENO6r0oWPtlo0gDAUFZAREY4twPkAR+JFmVSIFE6afuopm+KUlcesGNqlbiBF9hbh8pdQA+RSo3LMWcRor/d6g1F7JdJ12F2KY+F7jwB4SyQdcrIJc4dtim0VWYdf04NyEt70BOZnMYMpbTZYfqhuAX76HaP3xj4fvX/Wky+E10ckAkNPNTHFWdSR5od6bGF+NcKHaZHIkszty2TXymcOhy3kDx1ZrCga05KJhsNEvBNh09JmIrCiAjVdMrSx/yf3GdE812lDYriL0yzt9GYjnU25wK25HqH2JPLOAtbOqQdw4X/7eJ6a5QNLD3eeoK/BDN/Y+0c5IZBs2x5lct5KlzXqfbMp9jQxzYT1FBsK/RwNtQvh6gdP1l/+XLnrq8t09gBvpd1BzfrFRbNY1ZAu04FnWqgfB0py+FgAr1TCz+g53H6hc6nT74QZi6V37mTc6EDNn7MjR7Vmdg2dK0/08gaWOQkGMAyVfmSb6OOzG0dhAv89aCi4hiWdFGQBdboRz4qyhCWjy4wDn73EifzaCqR1E1dYZV4ywdzBr/bdyUDyWbq1FBEEKaE1chNkoH69q6JyLztDfRQZVDIF2zjZkMA7mQy0a0H8hhcbcLUDzuH0/vvz6yXx/3L/QFcaEmf/n7/vmJdNQKAiMUUaGBMcQAa4ZOA1XQVZ3IwtJH/4tjSC2rCx6/WvrAqsioiPx1WRcQ2qA5oa3H/oOKrHm+43Ct1zDt2pXj2LQ5sYJy6MFLqDoqdkXpEWemThvNGi8Tx/G+RN0vTd+gPmJIpjr6W8aqalr6fKxyVJNGXKJkSRBhn+oaOglWAWZN8pEsNcXUQg7op7lL9k4zICeTfZxJXmAhyeK6rfb7uV1gpi2rgWVQ3EOGayC6F3kFwUBU2A2894qSLYn0UVCI0P5rKQGmCSlRhxSqCEOdjJu49eng//C/GlM3q23i2wA7IgzMKi+bM5TWzpazqzdRB7AQ+8QcDN6EWKLD/tcPZ8+U+z53p+Pr24e75+PxSz2+awsMyKBqmviPv3/lhmRVlxRg4p8f96dfDmx9enp+ZuL1tWXvGsZRFTSkNeIoEhhutxdAVcU2Zd++vysoQhy078QD1LIoouEB51w+hhhlcvCrxdCWYBeOAfWlQ5uyBbAjJtyg3PUWyuIqSjcVKyBiRJcau5eet0EhIAvQsqXM0TgsfrifGRZrGMI0HSQjU3lvIttCjLkRG7wkQOa2OFa92JuEQclCkbsSxkQku2FBQW532QpXnUnFgjtA1qIacTIj4a4xxLhdtWRxitPPgYnGNSUhPDHlrRolTFNXiaUOiAuYjS0D/6ZaYiQrWxZXVmeNsg1UaAvqnoqiPPfqRdDcytvcsATq0EYvtw3dnBOXcsNuJTpC4X9PE6pdjg0yQxM5KxIasvtbokrPaQzTIMaYUOhrBxbX84DnXfzksneCk9qEvnQlOt7/gdpbs3U+UYF01A0y5XJsdQs0WodJMbWBxstGWD5HvdFGLG2pWc1Jcl/HWA7ZpkptlgAI/2V9AoEE98Dlc4aHA6hDUQZ5BbQ2F1kmougyzQNFztucXDfRuWPb03gsxeIOzWxGVme9JRDrlY/DNdwBG9+fva1+hDxq2qamz6EyVJtGfyNLOb+8n/76ePgbe8WdWfm1aVfd/RyyqsmQq6PAoE7V9Rlo8JFj0jR3Jaqtl3fbJesqr3CPidEco1nLojtiuylIrvVavZkz2lC/KzRNNa3JDEr7LQon3jE11I4wFfj709PrY1iPQl0cAja6OH6akYBblcnINOS8dew4ijYFj4IDt3V1Cl7jhEcoshISFn1djJ3v8GfOd2Su4kDEvT1KQFIwNdoELCDpR+gMccDgdRJsocLuHqo45ykoozatwww9CoC0c50CSxf5tY0x2XLXaFRoOoox6yUA2eD/HpAh5RpANZVZyFDE19wKqV0b5Ffabtt/Yb+/v+5/XnRmP14UiXxXx5rJnWZOu6aWo5k3IDK5+i9BBKUWINImvUUiksXr/z+ijx4i0idlhP6rWTpNUDay1bqhEj5Jo3QtN4alcXkuJM20uvO8jwN7PGkQL0XZGt3NrQu79xxoEU30b/Ziy6DEUYS7C6trbtHEx8ev7H7/+PSFFfuv+5enxeRGyNTqJEFcxtxSnbm0ryumYTpzQ544xboGGQnuiASuKBbjdWvVrMVG8wfAg0zKu33jvti4TZ1I2p5JmnwYRyhiw8aO88j8Onk6hSyfcyg6J+sFKk11qT0grmm6EUwURboKRCmRBHgOglFLYXBlpWp2YSb5EfViLJUr06mL2o62Qm1HCJ19dgT5HBglzrCXQ5E0AW9sGvzHOYOHQtVWnTkOouMKLh1p8bOmqvIKrCaERzNfFHEV+ktfBCyTrZpFsw0JFu8VonEC8Nz/mK7pCeKnSLXOA8tpBufIwh8d8byAUVDnMcdp6vBCTWvRW52czchlA+Bi1ixhs23ZLOnb9rlvXI983WjRbcZ8nGNAQLOBQZuzqdoC1kjbBS8HVj59PQye5oO8HNGXRYPMbsDEE9dvbJv7c6BWO8UyTWPW3Sw8bIEPrpZ+JD4Be+i3ZeHZEJD++Y/roeBmPeyKqrha0fLcumotZ1JHfVdhgdvcmxv2NsWwyCVdL13D85rdvCBEKPml57nxr7+36JSPw/HQoSqX26bebQ23Ex4HlzdMajfmoJ+lx4oqy9K8LKSs0GSw8bNoTRmgFt/1K6HhU020usdBR9T2mjwYOhAkTdlKgCyRrLxe43orNsDuhhsEUbUKk/S+K665WBn7pgrEbSZWwq8akK1njHz79HJ8e/wVJ7MoztFxX0L1x9S5ZB37UBxiAJ8BhpNjbX4ycj6zJpJ7NDwInbRFN9WHKicXezhtZ+HxkollFVvvNisMjeLm5BrSA0D67g7QbDWHJ1RwseFmtHLpZ7LuhM+WOYgwxhNbdaC9FXUyezZdx8aLaqkmzSZmHKl3Gpzbas2z2RoUC5mzaR7nvYL6mPiKOkf4mGC7E0nB4tSVOaxTRa/vQTlpT/CjQQmqaB1vQfgOK9H087IVGOdabNsHvtbVPR34AjkmbCkKoG6lrOXqvSvgcsFlD+Kn6cOFBPHho8Jxx+tGiLjSpNmymXleFj9zAMDroZxD5i+GFxFuYJQONZJ0bjhTBX5b3Q6EAJu2AKeiE/DJMChbh73a+be6Jf9iWOLG1InVjkJtRTNlG26k4RWLBE+h9TqovZNoE0ceCVqUITRimEODBb2bjx3bmtrxvXQV7kSwEw/nsMk+H7/+jH/xfx9B1pffySFujQXWzj5MODkTl40xRbVpIeY7vF5WiApJ+t+gabKMwad0c+KcZ99OgJ04i39FbwBrEXD6qeK7K1oT3J40EgioZd1Oq/3SJMAVBLnlP2YCGAF2MzXlp4grmkqUcs6Sde5grlLkWec1K0TktbI/iyLcNIipOoEsRHOffjlQJ/yhMKnXNFeRw4ZZTCqep1H0uewZ09RY1J7f4ktgmVD6XkU2d91HseUcypWxo7E9Y4PftdA4R9e0AYfnxbNXubQ3tXuXayAd9pYcCiSaII1ertEFCDnGMYiVTvK6hAa48FaY+BilIhGxbVD492R06Lxvj/uXQy3F6XMmOjJ3PAtO7ZKbJmVd0PBvyYU7x2dp9UwudPmLkeWAWQ1DdQ6UTBrgLRoGAZIF4kF7ES+9XUNuCCjDHY/eRjS2D3BDrnmo/TtaCHg9lKPz2yML5CFuqTLW33gSBg8VJtUmCQqAufjjh2F2FbcN62aeQTJVTdr6PTsLPRI8yJX5YoNDoKnWx+yK+Xnuolv6dxEMy3bmjjfkqR+USwjXFJwxIgLshgtPTmfPh++5o1mKvITi+enz7+wDOPLrCCQuD4Wtc/eC4toror7D4B0PICqpwe+6ianKFcO2jNutzlZ0m8sCgRW9jcMCZ1QM05wggvawkLvSRbBcdEjsUP7X5R45sESDJmODz1fPN0flV7H4abC8nBrq1lE4sc6pa9xeJRqMuJCrLINTGLs54tp4AxIFr9uPW/pd66ZEMN4G1ejMbN2/mk+jtDohz4N4aRbJSqPd+4cq6cf6GgwkaNRHapH8Jc76QZVdSx+GaMpaWddo7fEPJAEbmxXkjrnn93YStsHWO68k4C5yJVtt9dVtaxzRQmW3uZhZeYMDUG7QiPvf7ACOYpnSYb7rzsBLmuhdHDhzQYyc25qaZk9hVHpOYsqGyWRvB8+3IVasouSm4KBt1ieAhzfM6UoFDj5Au/6TJ1Ps9j1gCo4Zac4Ws3V37S5fig2jrwgjW8ias0rqHDUZds9ZCq9IorWK9Mvx9KHO/QMCA6XqKl2O1O+HYzdBlEwOnoYJyOSJZAMvbsPTtbSBT0g+TyFxVF2jYV2O1/z44lKONSClwD1xAWbH6qsMMKo0b5RKwB3SAd+d8AeKvn6Cp971qeqrZ2umrtUDd9drt10I7AaHVlkmzsefBjYCHwJBDa7G0v5m0itM2nkyuDLpuUqnFDNM3alFW7e22otPINeQrgO6vFp0ygt4K8i8a6K9Hi4Y6hJZFBRxGXziFFnfBLhu6NMm4AaAWd7cRbBu0f2o/wJzUiDpji1W9i1UXpqai7wjv/XxG/Yc9q+YJ+fviRxvFgEJULluT3VdB1DRUdU1kJqgPbKpicI6RcrJWh1XUd8y4HpglW51af/V16WO8zootk1LmTof2LdAW6d96ZGOFkgKw16P343ubs2lNz9RdYVrw1eB9mVoqnKNK4vaExQ681bhyDRmm9RPgOJJhTfNLqS20NWDQ1kyztQ+cn2RQ3SklYa79xe6mPFD+u0wChRKYlWnm4SGgOJQOvNcN6C7OLogU0hteEfOFac3fcvx+YILrtnqjYrG7W3T4oacR4m1j43xbqiJU/Yg7sTQIYrOQKr2luELAAxcWMFiUJ29/phQ/uV/AA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"RNP Number" = _t, #"Service Centre" = _t, #"Engineer Name" = _t, State = _t, City = _t, #"Model Code" = _t, #"Defect Category" = _t, Status = _t, #"Serial No" = _t, #"AC Error Code" = _t, #"Days Open" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"State", type text}, {"City", type text}, {"Model Code", type text}, {"Defect Category", type text}, {"Status", type text}, {"Serial No", type text}, {"AC Error Code", type text}, {"Days Open", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

