table RNPs
	lineageTag: 9a31909d-04f6-4e5b-8d2b-0dc2bc2c34c7

	measure 'FTF Failure%' = 260/780
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3787466c-8643-4997-aaee-4266e61485f5

	measure 'Parts Replacement%' = 0.612
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4b11eb91-04f7-45a0-a086-4cfa5d3fe1cb

	measure 'total rnps val' = 2543
		formatString: 0
		lineageTag: bc8388c2-7b9f-4062-8f8f-19745492f873

	measure RNPS = 7862
		formatString: 0
		lineageTag: f7f4b08f-b1c3-4444-bd19-91f8b0944fff

	measure 'Open calls  status' = ```
			2485 
			```
		formatString: 0
		lineageTag: f5c0779a-694a-4c5e-b6dd-d818a7a7725d

	measure 'Hold Status Call' = 1056
		formatString: 0
		lineageTag: bd9a1043-0189-428c-bd74-40892ce8170a

	measure 'closed status calls' = 2974
		formatString: 0
		lineageTag: f06fe438-1155-43a9-9ff2-497c1732f401

	measure 'Returned status call' = 1347
		formatString: 0
		lineageTag: e073d886-3264-433a-95aa-24ea9fadcb3d

	column 'Total RNP'
		dataType: int64
		formatString: 0
		lineageTag: 366795d0-e890-4f64-9354-9261bc52ba3b
		summarizeBy: sum
		sourceColumn: Total RNP

		annotation SummarizationSetBy = Automatic

	column Open
		dataType: int64
		formatString: 0
		lineageTag: 6b22219b-1eea-4fd6-81dc-f9e8bef81b01
		summarizeBy: sum
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

	column Hold
		dataType: int64
		formatString: 0
		lineageTag: c51e5af4-b007-41d6-a8be-df2273ed5cd1
		summarizeBy: sum
		sourceColumn: Hold

		annotation SummarizationSetBy = Automatic

	column Returned
		dataType: int64
		formatString: 0
		lineageTag: 7695c871-66d0-43ca-9f17-ea486b34d989
		summarizeBy: sum
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column Closed
		dataType: int64
		formatString: 0
		lineageTag: 3fa420ae-8848-4166-849e-73f871ac22bb
		summarizeBy: sum
		sourceColumn: Closed

		annotation SummarizationSetBy = Automatic

	partition RNPs = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMjQwUNJRMjMFEqYglimIZWmgFBsLAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Total RNP" = _t, Open = _t, Hold = _t, Returned = _t, Closed = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Total RNP", Int64.Type}, {"Open", Int64.Type}, {"Hold", Int64.Type}, {"Returned", Int64.Type}, {"Closed", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

