table 'State city master'
	lineageTag: 2193d597-7bb6-45d0-a6cc-ce93adfc97e4

	measure 'Highest Failing State' =
			
			VAR T =
			    TOPN(
			        1,
			        SUMMARIZE(
			            'State city master',
			            'State city master'[State],
			            "Failure", SUM('State city master'[Custom])
			        ),
			        [Failure],
			        DESC
			    )
			RETURN
			MAXX(T, [State])
		formatString: 0
		lineageTag: ef2879fc-a69f-4678-bd36-b93a840b6046

	measure Failing% = Calculate(SUM('State city master'[Custom]),'State city master'[State]="Delhi")
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c1a09969-f5c9-4e16-b6a6-f7ad043a8262

	column State
		dataType: string
		lineageTag: 1af1af39-6de5-4352-a994-3f97b6ab5972
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 5c2afdfe-9fd9-4649-85d5-3d40317d0630
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Total
		dataType: int64
		formatString: 0
		lineageTag: 6750294f-9f9e-4643-9777-d477ed20333f
		summarizeBy: sum
		sourceColumn: Total

		annotation SummarizationSetBy = Automatic

	column Open
		dataType: int64
		formatString: 0
		lineageTag: 2fbfe498-9256-4b91-9681-b2c32a689d87
		summarizeBy: sum
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

	column Hold
		dataType: int64
		formatString: 0
		lineageTag: c02d7a2c-b757-43ac-bdf9-bb445dca1844
		summarizeBy: sum
		sourceColumn: Hold

		annotation SummarizationSetBy = Automatic

	column 'Failure %'
		dataType: string
		lineageTag: c9516a63-daa9-46f5-bf22-6e4c796284fb
		summarizeBy: none
		sourceColumn: Failure %

		annotation SummarizationSetBy = Automatic

	column 'Text Before Delimiter'
		dataType: double
		lineageTag: e3d1e5e5-4939-4931-832e-41137df840c9
		summarizeBy: sum
		sourceColumn: Text Before Delimiter

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Custom
		dataType: double
		lineageTag: 4e81fca5-7a68-4d19-bf90-7e294cfff79b
		summarizeBy: sum
		sourceColumn: Custom

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Branch
		dataType: string
		lineageTag: 17590de2-a06b-4547-a8f5-811f6e06f60a
		summarizeBy: none
		sourceColumn: Branch

		annotation SummarizationSetBy = Automatic

	partition 'State city master' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("jZNLb4JAEMe/ijHpzRCWh+gRH8VH2zRa24PxMApxUQSzgE2/fXdmu7Yitr0Mu2R+8/zvctn005ALaDwLCKOcN1vyB6QFHEshz44njeWisfBqsDv5eRnPmqtWDdqL93s4ZUkpzzbTxkTc8JB8Hc/ryT6PiyLLMKft6JxdvBnmrymHkBeNIAvhBCKWd5fSdqRhNlXs/po3yFJCNUTGpLyOAicKzHM4YIcgjlEBt/oLFm8X7n3YcBX8P94DEALS7U9POtxyj9ei3ILgt4qvAkEGyREE/OU/iBKOs9Rf28FNWB7W4hFoGh0EBsOHC+Apem+cobqONRCUO1lHgWrjhyiENYQYGz1dT++ubVjI+KPHKnMQUYI52NkXNcPUrmf+pOovFY3xGbbBzC9lMVXSdfgepJDv5SPgNClLy5Hegmq8BpJ7Ljdc10PGpCz0ZOYLpd8RiA8ZXv65l3rVjdeLNrhiglJsIUtxNrY2NDOjXQ+M4pzk5zi0NUygJtWt959w2O2+CTJKIARM/SowhViOKdHRTX2wVEUErD4B", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t, Total = _t, Open = _t, Hold = _t, #"Failure %" = _t, Branch = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Total", Int64.Type}, {"Open", Int64.Type}, {"Hold", Int64.Type}}),
				    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Changed Type", "Text Before Delimiter", each Text.BeforeDelimiter([#"Failure %"], "%"), type text),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Inserted Text Before Delimiter",{{"Text Before Delimiter", type number}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type1", "Custom", each [Text Before Delimiter]/100),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Custom",{{"Column1", "State"}, {"Column2", "City"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

