table Sub-product
	lineageTag: 6207c8b7-58de-4111-9746-bae4a6bfdcb1

	column Catg
		dataType: string
		lineageTag: 8125d128-9506-46f5-8f1a-869d4ff95999
		summarizeBy: none
		sourceColumn: Catg

		annotation SummarizationSetBy = Automatic

	column Count
		dataType: int64
		formatString: 0
		lineageTag: d19b580c-6c21-4292-9a89-3aad49ade209
		summarizeBy: sum
		sourceColumn: Count

		annotation SummarizationSetBy = Automatic

	partition Sub-product = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCg5ydFbSUTI3MVCK1YlWCs/MA/KMTCE8z7wyBbC0oYmxUmwsAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Catg = _t, Count = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Catg", type text}, {"Count", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

