table 'Warranty Type KPI'
	lineageTag: 318866cb-b781-4bb5-8080-36bc21841201

	column Type
		dataType: string
		lineageTag: c4a365ab-08a9-4406-b506-ad10d698c579
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Count
		dataType: int64
		formatString: 0
		lineageTag: 1f20961b-aad7-43e7-a49c-c6a6fc9a3c10
		summarizeBy: sum
		sourceColumn: Count

		annotation SummarizationSetBy = Automatic

	partition 'Warranty Type KPI' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8szTDU8sKkrMK6lU0lGytDRQitWJVvIvLUEWNjQ2VoqNBQA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Type = _t, Count = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Type", type text}, {"Count", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

